### PR TITLE
Add blob support to `_assertDeepEqual`

### PR DESCRIPTION
**Pull request by mm-gmbd**
Add blob support for PR #10

### CODE REVIEW

**Comment by alexey-nbl** [comment]
It is [recommended](https://developer.electricimp.com/squirrel/squirrel-guide/variables-strings-blobs#comparing-blobs) to compare blobs by the one imp API method - [crypto.equals()](https://developer.electricimp.com/api/crypto/equals) that would make the code much simpler.

Or do you need to print out the details of the comparison, like the "index" of the first non-equal byte, etc?

**Comment by mm-gmbd** [comment]
I don't think printing out the first non-equal byte is necessary, so yes this could be updated to use `crypto.equals()`.

**Comment by mm-gmbd** [comment]
Updated to use `crypto.equals()` -- @alexey-nbl, does this look okay?

**Comment by alexey-nbl** [comment]
If you manually tested it, it's ready.

**Comment by mm-gmbd** [comment]
:) will let you know soon

**Comment by alexey-nbl** [comment]
oh... seems, it would be also good to add a check that value2 is a blob as well.
W/o such a check, value2.len() may return "ERROR: the index 'len' does not exist", if, for example, value2 is an integer.

**Comment by mm-gmbd** [comment]
I thought that was already in there, good catch!

**Pull request merged**
